# Generated by Django 3.0.4 on 2020-04-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
